resolver: lts-9.0
packages:
- '.'
extra-deps:
#- haskey-btree-0.2.0.1
- git: https://github.com/haskell-haskey/haskey-btree
  commit: 4ff3a73d8eb480902478772f1be5515967624ff6
- lz4-0.2.3.1
- numerals-0.4.1
- xxhash-ffi-0.2.0.0
flags: {}
extra-package-dbs: []
