name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  - push
  - pull_request

jobs:
  cabal:
    name: cabal ${{ matrix.cabal }} / ${{ matrix.os }} / ghc ${{ matrix.ghc }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        cabal:
          - "3.2"
        ghc:
          - "8.6"
          - "8.8"
          - "8.10"
        exclude:
          - os: macOS-latest
            ghc: 8.8.4
          - os: macOS-latest
            ghc: 8.6.5

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1.1.7
        id: setup-haskell-cabal
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Configure
        run: |
          cabal configure --enable-tests --enable-benchmarks --test-show-details=direct

      - uses: actions/cache@v2
        name: Cache ~/.cabal/store and build files
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-cabal

      - name: Install dependencies
        run: |
          cabal build all --only-dependencies

      - name: Build
        run: |
          cabal build all

      - name: Test
        run: |
          cabal test all

  stack:
    name: stack / ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest

    runs-on:
      - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1.1.7
        with:
          enable-stack: true
          stack-version: latest

      - uses: actions/cache@v2
        name: Cache ~/.stack
        with:
          path: |
            ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-stack-

      - name: Install dependencies
        run: |
          stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build
        run: |
          stack build --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: |
          stack test
